LaptopStore/Controllers/AccountController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using Account.Entity;

namespace LaptopStore.Controllers
{
    public class AccountController : Controller
    {
        // GET: Account
        accountRepository acc;
       public AccountController()
        {
            acc = new accountRepository();
        }
        public ActionResult Login()
        {
            IEnumerable<Accounts> Ids = acc.GetAllAccounts();
            return View(Ids);
        }
        [HttpPost]
        public ActionResult Login(Accounts ids)

        {
            bool status= accountRepository.CheckIds(ids);
            if (status)
            {
                if (ModelState.IsValid)
                {
                    return RedirectToRoute("www.google.com");
                }
            }
            else
            {
                Response.Write("Invalid");
            }
            return View();

        }
        public ActionResult SignIn()
        {
            if (ModelState.IsValid)
            {
                return View();
            }
            return View();
           
        }
    }
}

LaptopStore/Controllers/DefaultController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using Laptop.Entity;
using LaptopItems;

namespace LaptopStore.Controllers
{
    public class DefaultController : Controller
    {
        // GET: Default
        LaptopRepository laptop;
        public DefaultController()
        {
            laptop = new LaptopRepository();
        }
        public ActionResult Index()
        {
            IEnumerable<LaptopSpecification> specifications = laptop.GetAllLaptopDetails();
            return View();
        }

        
        public ActionResult Create()
        {
            return View();
        }

       
        [HttpPost]
        public ActionResult Create(LaptopSpecification product)
        {
            laptop.AddLaptop(product);
            TempData["Message"] = "Item added successfully";
            return RedirectToAction("Index");
        }

       
        public ActionResult Delete(int id)
        {
            laptop.DeleteEmployee(id);
            TempData["Message"] = "Item Deleted Successfully!";
            return RedirectToAction("Index");
            
        }



    }
}

LaptopStore/Controllers/LaptopController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using LaptopItems;
using Laptop.Entity;

namespace LaptopStore.Controllers
{
    public class LaptopController : Controller 



    {
        // GET: Laptop
        LaptopRepository laptop;
        public LaptopController()
        {
            laptop = new LaptopRepository();
        }
        public ActionResult Index()
        {
            IEnumerable<LaptopSpecification> specifications = laptop.GetAllLaptopDetails();
            return View(specifications);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(LaptopSpecification product)
        {
            laptop.AddLaptop(product);
            TempData["Message"] = "Item added successfully";
            return RedirectToAction("Index");
        }


        public ActionResult Delete(int id)
        {
            laptop.DeleteItem(id);
            TempData["Message"] = "Item Deleted Successfully!";
            return RedirectToAction("Index");

        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
           LaptopSpecification specification= laptop.GetLaptopById(id);
            return View(specification);

        }
        [HttpPost]
        public ActionResult Update(LaptopSpecification specification)
        {
            laptop.UpdateItems(specification);
            TempData["Message"] = "Item Updated Successfully!";
            return RedirectToAction("Index");
        }
      
    }
}

LaptopStore/Views/Laptop/Create.cshtml
@model Laptop.Entity.LaptopSpecification

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>
@using (Html.BeginForm("Create", "Laptop"))
{
    <table border="1">
        <tr>
            <td>ID :</td>
            <td> @Html.TextBoxFor(Model => Model.Id)</td>
        </tr>
        <tr>
            <td>Laptop Brand : </td>
            <td>@Html.TextBoxFor(Model => Model.Brand)</td>
        </tr>
        <tr>
            <td>Price : </td>
            <td>@Html.TextBoxFor(Model => Model.Price)</td>
        </tr>
        <tr>
            <td>Description: </td>
            <td>@Html.TextBoxFor(Model => Model.Description)</td>
        </tr>

        <tr>
            <td>
                <input type="submit" />
            </td>
            <td><a href="/Index">Back</a></td>
        </tr>
    </table>
}

LaptopStore/Views/Laptop/Edit.cshtml
@model Laptop.Entity.LaptopSpecification

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm("Update", "Laptop", FormMethod.Post))
{
    @Html.HiddenFor(Model => Model.Id);
    <table border="1">
        <tr>
            <td>ID :</td>
            <td></td>
        </tr>
        <tr>
            <td>Laptop Brand : </td>
            <td>@Html.TextBoxFor(Model => Model.Brand)</td>
        </tr>
        <tr>
            <td>Price : </td>
            <td>@Html.TextBoxFor(Model => Model.Price)</td>
        </tr>
        <tr>
            <td>Description: </td>
            <td>@Html.TextBoxFor(Model => Model.Description)</td>
        </tr>

        <tr>
            <td>
                <input type="submit" value="Submit" />
            </td>
            <td><a href="/Laptop">Back</a></td>
        </tr>
    </table>
}

LaptopStore/Views/Laptop/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<h2>Welcome</h2>
@if (TempData["Message"] != null)
{
    @Html.Label((string)TempData["Message"])
}
<br />
@Html.ActionLink("Add New Laptop", "Create")
<table border="1">
    <tr>
        <th>Id</th>
        <th>Laptop Brand</th>
        <th>Price</th>
        <th>Decription</th>
        <td>Action</td>

    </tr>
    @foreach (Laptop.Entity.LaptopSpecification product in Model)
    {
        <tr>
            <td>@product.Id</td>
            <td>@product.Brand</td>
            <td>@product.Price</td>
            <td>@product.Description</td>

            <td>
                @Html.ActionLink("Edit", "Edit", new { id = product.Id })
                @Html.ActionLink("Delete", "Delete", new { id = product.Id })
            </td>
        </tr>
    }
</table>

LaptopStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Login", "Login", "Account", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Signin", "SignIn", "Account", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">

                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    @RenderSection("Validation", false)


</body>
</html>